export const REQ_NOWMOVIES='reqnowmovies'
export const REQ_COMINGMOVIES='req_comingmovies'
export const REQ_TOP250='req_top250'
export const REQ_MORETITLE='req_moretitle'
export const CLEAR='clear'
export const SETUSER='setuser'
export const CLEARUSER='clearuser'
